data = {
    "Movements": {
        "Vertical Movements": [
            "j - Move one line down",
            "k - Move one line up",
            "] - Jump to the next paragraph",
            "[ - Jump to the previous paragraph",
            "gg - Go to the beginning of the file",
            "G - Go to the end of the file",
            "Ctrl + d - Scroll down half a page",
            "Ctrl + u - Scroll up half a page",
            "zz - Center the current line in the middle of the screen",
            "zt - Move the current line to the top of the screen",
        ],
        "Horizontal Movements": [
            "h - Move one character to the left",
            "l - Move one character to the right",
            "w - Jump to the start of the next word",
            "e - Jump to the end of the current/next word",
            "b - Jump to the start of the current/previous word",
            "W - Jump to the start of the next word, ignoring punctuation",
            "B - Jump to the start of the previous word, ignoring punctuation",
            "E - Jump to the end of the next word, ignoring punctuation",
            "0 - Move to the start of the current line",
            "$ - Move to the end of the current line",
            "% - Jump between matching brackets [] {} ()",
            "f<char> - Move to the next occurrence of <char> in the current line",
            "t<char> - Move to just before the next occurrence of <char>",
            "F<char> - Move to the previous occurrence of <char>",
            "T<char> - Move to just after the previous occurrence of <char>",
            "; - Repeat the last f or t command forward",
            ", - Repeat the last f or t command backward",
        ],
    },
    "Editing Text": {
        "Deleting Text": [
            "x - Delete the character under the cursor",
            "X - Delete the character before the cursor",
            "r<char> - Replace the character under the cursor with <char>",
            "R - Overwrite text starting from the cursor",
            "dw - Delete from the cursor to the start of the next word",
            "de - Delete from the cursor to the end of the current/next word",
            "db - Delete from the cursor to the start of the current/previous word",
            "daw - Delete the word and its surrounding spaces",
            "diw - Delete the word without surrounding spaces",
            "da+([{<'\" - Delete text inside and including brackets/quotes",
            "di+([{<'\" - Delete text inside brackets/quotes only",
            "df<char> - Delete from the cursor to <char>",
            "dt<char> - Delete up to, but not including, <char>",
        ],
        "Cutting and Changing Text": [
            "c - Delete text and switch to insert mode",
            "s - Delete the character under the cursor and switch to insert mode",
            "dd - Delete the entire current line",
            "D - Delete from the cursor to the end of the line",
            "C - Delete from the cursor to the end of the line and switch to insert mode",
            "S - Delete the entire line and switch to insert mode",
        ],
    },
    "Copying and Pasting": {
        "Copying": [
            "yy - Copy the entire current line",
            "y + w,e,b,i,a - Copy text using the same movement rules as deletion commands",
        ],
        "Pasting": ["p - Paste after the cursor", "P - Paste before the cursor"],
    },
    "Visual Mode": {
        "Visual Selection": [
            "v - Start character-based selection",
            "V - Start line-based selection",
            "Ctrl + v - Start block (column) selection",
            "v + w,e,b,i,a - Extend the selection using movement commands",
        ],
        "Visual Mode Actions": [
            "d - Delete the selected text",
            "y - Copy the selected text",
            "~ - Toggle the case of the selected text",
            "p - Paste after the selection",
            "P - Paste before the selection",
        ],
    },
    "Indentation": [
        ">> - Indent the current line to the right",
        "<< - Indent the current line to the left",
        "> - Indent selected lines to the right",
        "< - Indent selected lines to the left",
    ],
    "Inserting Text": [
        "i - Insert text before the cursor",
        "a - Insert text after the cursor",
        "I - Insert text at the beginning of the line",
        "A - Insert text at the end of the line",
        "o - Insert a new line below the current line",
        "O - Insert a new line above the current line",
    ],
    "Search and Replace": [
        "/pattern - Search for a specific pattern in the file",
        "* - Search for the word under the cursor",
        "n - Jump to the next search match",
        "N - Jump to the previous search match",
        ":%s/old/new/g - Replace all occurrences of 'old' with 'new' in the file",
        ":%s/old/new/gc - Replace all occurrences with confirmation",
    ],
}
